# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.13
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: "sudo apt-get update; 
              sudo apt-get update -y;
              sudo apt-get install build-essential;
              sudo apt-get install git;
              git clone https://github.com/etivvenkata/etivvenkata.github.io.git;
              cd /home/circleci/project/etivvenkata.github.io;
              g++ giggle.c -o giggle;
              ./giggle;
              sudo mkdir -p /giggle/DEBIAN;
              sudo touch /giggle/DEBIAN/control;
              sudo chmod 777 /giggle/DEBIAN/control;
              sudo echo Package: giggle >> /giggle/DEBIAN/control;
              sudo echo Version: 1.0 >> /giggle/DEBIAN/control;
              sudo echo Section: custom >> /giggle/DEBIAN/control;
              sudo echo Priority: Optional>> /giggle/DEBIAN/control;
              sudo echo Architecture: all >> /giggle/DEBIAN/control;
              sudo echo Essential: no  >> /giggle/DEBIAN/control;
              sudo echo Installed-Size: 1024 >> /giggle/DEBIAN/control;
              sudo echo Maintainer: Venkata.org >> /giggle/DEBIAN/control;
              sudo echo Description: Print the project on the screen >> /giggle/DEBIAN/control;
              sudo mkdir -p /giggle/usr/bin/;
              sudo cp  /home/circleci/project/giggle /giggle/usr/bin;
              sudo dpkg-deb --build /giggle;
              sudo mv /giggle.deb /giggle-1.0_amd64.deb;
              sudo cp /home/circleci/project/giggle  /home/circleci/etivvenkata.github.io ;
              git config --global user.name etivvenkata;
              git config --global user.email etivvenkata@gmail.com;
              cd  /home/circleci/project/etivvenkata.github.io;
              ./giggle > index.html ; cat index.html"


    





